# Generated by Django 5.1.6 on 2025-02-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='sub_team',
        ),
        migrations.AddField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(default='iVista', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(default='Solutions', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subteam',
            field=models.CharField(blank=True, choices=[('SEO', 'SEO'), ('SMO', 'SMO'), ('SEM', 'SEM'), ('Design', 'Design Team'), ('Content Writing', 'Content Writing'), ('Python Development', 'Python Development'), ('Web Development', 'Web Development')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='team',
            field=models.CharField(blank=True, choices=[('Search', 'Search Team'), ('Creative', 'Creative Team'), ('Development', 'Development Team')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='usertype',
            field=models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('TeamLeader', 'TeamLeader'), ('User', 'User')], max_length=50),
        ),
    ]
