# Generated by Django 5.1.6 on 2025-02-15 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0002_remove_customuser_sub_team_customuser_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('team', models.CharField(choices=[('Search', 'Search Team'), ('Creative', 'Creative Team'), ('Development', 'Development Team')], max_length=50)),
                ('subteam', models.CharField(blank=True, choices=[('SEO', 'SEO'), ('SMO', 'SMO'), ('SEM', 'SEM'), ('Design', 'Design Team'), ('Content Writing', 'Content Writing'), ('Python Development', 'Python Development'), ('Web Development', 'Web Development')], max_length=50, null=True)),
                ('account_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_teams', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL)),
                ('team_leader_creative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='led_creative_teams', to=settings.AUTH_USER_MODEL)),
                ('team_leader_development', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='led_development_teams', to=settings.AUTH_USER_MODEL)),
                ('team_leader_search', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='led_search_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
