# Generated by Django 5.1.6 on 2025-02-17 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0010_remove_task_assigned_users_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='timesheet_app.team'),
        ),
    ]
