# Generated by Django 5.1.6 on 2025-02-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0011_project_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='team',
        ),
    ]
