# Generated by Django 5.1.6 on 2025-02-25 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0018_remove_task_assigned_by_remove_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('task', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('To Do', 'To Do'), ('On Progress', 'On Progress'), ('On Hold', 'On Hold'), ('Completed', 'Completed')], default='To Do', max_length=20)),
                ('description', models.TextField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_timesheets', to=settings.AUTH_USER_MODEL)),
                ('submitted_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_timesheets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
