# Generated by Django 5.1.6 on 2025-02-25 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0019_timesheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesheetTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_timesheet_tables', to=settings.AUTH_USER_MODEL)),
                ('timesheets', models.ManyToManyField(related_name='timesheet_tables', to='timesheet_app.timesheet')),
            ],
        ),
    ]
