# Generated by Django 5.1.6 on 2025-02-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0020_timesheettable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='hours',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
