# Generated by Django 5.1.6 on 2025-02-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0021_alter_timesheet_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheettable',
            name='status',
            field=models.CharField(choices=[('Pending Review', 'Pending Review'), ('Approved by Team Leader', 'Approved by Team Leader'), ('Rejected by Team Leader', 'Rejected by Team Leader')], default='Pending Review', max_length=50),
        ),
    ]
