# Generated by Django 5.1.6 on 2025-02-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0022_timesheettable_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheettable',
            name='status',
            field=models.CharField(choices=[('Pending Review', 'Pending Review'), ('Sent for Review', 'Sent for Review'), ('Approved by Team Leader', 'Approved by Team Leader'), ('Rejected by Team Leader', 'Rejected by Team Leader')], default='Pending Review', max_length=50),
        ),
    ]
