# Generated by Django 5.1.6 on 2025-02-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0023_alter_timesheettable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheettable',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
