# Generated by Django 5.1.6 on 2025-02-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0024_timesheettable_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chat_id',
            field=models.CharField(default='1234567890', max_length=50),
        ),
        migrations.AlterField(
            model_name='timesheettable',
            name='status',
            field=models.CharField(choices=[('Pending Review', 'Pending Review'), ('Sent for Review', 'Sent for Review'), ('Approved by Team Leader', 'Approved by Team Leader'), ('Rejected by Team Leader', 'Rejected by Team Leader'), ('Approved by Admin', 'Approved by Admin'), ('Rejected by Admin', 'Rejected by Admin')], default='Pending Review', max_length=50),
        ),
    ]
