# Generated by Django 5.1.6 on 2025-02-28 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0025_customuser_chat_id_alter_timesheettable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='timesheet_app.project'),
        ),
    ]
