# Generated by Django 5.1.6 on 2025-03-03 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0026_timesheet_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user_assigned_to',
        ),
        migrations.AddField(
            model_name='task',
            name='superadmin_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superadmin_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
